# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainFormUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QLabel, QFileDialog
from PyQt5 import uic
from potato import Ui_PotatoWindow
from padi import Ui_PadiWindow
import sys

class Ui_MainFormUI(object):
    def setupUi(self, MainFormUI):
        MainFormUI.setObjectName("MainFormUI")
        MainFormUI.resize(321, 183)
        self.centralwidget = QtWidgets.QWidget(MainFormUI)
        self.centralwidget.setObjectName("centralwidget")
        self.btnShowKentang = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowKentang.setGeometry(QtCore.QRect(10, 10, 300, 50))
        self.btnShowKentang.setObjectName("btnShowKentang")
        self.btnShowKentang.clicked.connect(self.bukawindowkentang)
        self.btnShowPadi = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowPadi.setGeometry(QtCore.QRect(10, 70, 300, 50))
        self.btnShowPadi.setObjectName("btnShowPadi")
        self.btnShowPadi.clicked.connect(self.bukawindowpadi)
        MainFormUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainFormUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 26))
        self.menubar.setObjectName("menubar")
        MainFormUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainFormUI)
        self.statusbar.setObjectName("statusbar")
        MainFormUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainFormUI)
        QtCore.QMetaObject.connectSlotsByName(MainFormUI)

    def bukawindowkentang(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PotatoWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def bukawindowpadi(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PadiWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainFormUI):
        _translate = QtCore.QCoreApplication.translate
        MainFormUI.setWindowTitle(_translate("MainFormUI", "Main Form"))
        self.btnShowKentang.setText(_translate("MainFormUI", "Potato"))
        self.btnShowPadi.setText(_translate("MainFormUI", "Rice"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainFormUI = QtWidgets.QMainWindow()
    ui = Ui_MainFormUI()
    ui.setupUi(MainFormUI)
    MainFormUI.show()
    sys.exit(app.exec_())
